import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App - 个人博客",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="root" className="flex flex-col">
          <div className="text-center py-5 bg-slate-700">个人博客</div>
          <div className="flex-1 overflow-y-auto">{children}</div>
          <div className="text-center py-5 bg-slate-500">Nextjs Study</div>
        </div>
      </body>
    </html>
  );
}
